import { NextResponse } from 'next/server';
import connectToDatabase from '@/lib/db';
import Car, { ICarSchema } from '@/models/Car';

const SEED_CARS: ICarSchema[] = [
  // ==========================================
  // 1. SPOR & COUPE (SUPERCAR & GRAND TOURER)
  // ==========================================
  {
    brand: 'Porsche',
    model: '911 Carrera 4S',
    year: 2024,
    category: 'Spor',
    transmission: 'PDK',
    fuelType: 'Benzin',
    capacity: 4,
    tankOrBattery: '64 L',
    horsepower: 443,
    acceleration: '3.4s 0-100',
    topSpeed: '306 km/s',
    dailyPrice: 16500,
    discountPrice: 14900,
    features: [
      'Sport Chrono Paketi',
      'PASM Spor Süspansiyon (-10mm)',
      'Bose Surround Ses Sistemi',
      'Spor Egzoz Sistemi (Gümüş Uçlu)',
      'Adaptif Hız Sabitleyici',
    ],
    description:
      'Safkan spor otomobil ikonu. Porsche 911 Carrera 4S; nefes kesen ivmelenmesi, efsanevi arkadan motorlu ağırlık dengesi ve akıllı dört çeker sistemiyle her virajda benzersiz bir sürüş hassasiyeti sunar.',
    isAvailable: true,
    isPopular: true,
    rating: 4.98,
    reviewCount: 94,
    location: 'İstanbul, Beşiktaş / Bebek',
  },
  {
    brand: 'Porsche',
    model: '911 GT3 RS',
    year: 2025,
    category: 'Spor',
    transmission: 'PDK',
    fuelType: 'Benzin',
    capacity: 2,
    tankOrBattery: '64 L',
    horsepower: 518,
    acceleration: '3.2s 0-100',
    topSpeed: '296 km/s',
    dailyPrice: 38000,
    discountPrice: 34500,
    features: [
      'Weissach Hafifletme Paketi',
      'DRS (Drag Reduction System) Aktif Kanat',
      'PCCB Karbon Seramik Frenler',
      'Karbon Fiber Yarış Koltukları',
      'Magnesium Dövme Jantlar',
    ],
    description:
      'Pistin en saf haliyle caddede buluşması. Doğal emişli 4.0 litrelik boxer motorun 9.000 devirdeki eşsiz çığlığı, aktif DRS aero kanadı ve yarış seviyesinde yol tutuş dinamiği.',
    isAvailable: true,
    isPopular: true,
    rating: 5.0,
    reviewCount: 42,
    location: 'İstanbul, İstinyePark VIP',
  },
  {
    brand: 'Ferrari',
    model: 'Roma',
    year: 2024,
    category: 'Spor',
    transmission: 'Otomatik',
    fuelType: 'Benzin',
    capacity: 4,
    tankOrBattery: '80 L',
    horsepower: 612,
    acceleration: '3.4s 0-100',
    topSpeed: '320 km/s',
    dailyPrice: 42000,
    discountPrice: 38500,
    features: [
      '3.9L Çift Turbo V8 Ödüllü Motor',
      'Side Slip Angle Control (SSC 6.0)',
      'Matrix LED Farlar',
      'Yolcu Tarafı Özel Bilgi Ekranı',
      'JBL Professional Surround Ses',
    ],
    description:
      'La Nuova Dolce Vita felsefesi. İtalyan zarafetinin 612 beygirlik V8 çift turbo güç ünitesiyle harmanlandığı, akıcı hatları ve lüks kokpitiyle büyüleyici bir Grand Tourer.',
    isAvailable: true,
    isPopular: true,
    rating: 4.97,
    reviewCount: 56,
    location: 'İstanbul, Maslak Finans Merkezi',
  },
  {
    brand: 'Ferrari',
    model: 'F8 Tributo',
    year: 2024,
    category: 'Spor',
    transmission: 'Otomatik',
    fuelType: 'Benzin',
    capacity: 2,
    tankOrBattery: '78 L',
    horsepower: 710,
    acceleration: '2.9s 0-100',
    topSpeed: '340 km/s',
    dailyPrice: 48000,
    features: [
      '710 HP Ortadan Motorlu Twin Turbo V8',
      'Ferrari Dynamic Enhancer (FDE+)',
      'Karbon Fiber Yarış Direksiyonu & LED Devir Göstergesi',
      'Brembo Karbon Seramik Diskler',
      'Aktif Difüzör ve S-Duct Kanalları',
    ],
    description:
      'Maranello mühendisliğinin doruk noktası. 710 beygirlik ortadan motor yerleşimi, 2.9 saniyelik soluk kesici hızlanması ve aerodinamik şaheser S-Duct hava tüneli.',
    isAvailable: true,
    isPopular: false,
    rating: 4.99,
    reviewCount: 31,
    location: 'Muğla, Bodrum Marina / Yalıkavak',
  },
  {
    brand: 'Lamborghini',
    model: 'Huracan Evo',
    year: 2024,
    category: 'Spor',
    transmission: 'Otomatik',
    fuelType: 'Benzin',
    capacity: 2,
    tankOrBattery: '83 L',
    horsepower: 631,
    acceleration: '2.9s 0-100',
    topSpeed: '325 km/s',
    dailyPrice: 46000,
    discountPrice: 42000,
    features: [
      '5.2 Litre V10 Doğal Emişli Canavar',
      'LDVI Dinamik Araç Entegrasyon Beyni',
      'Dört Tekerden Yönlendirme (AWS)',
      'Sensori Alcantara Yarış Koltukları',
      'Spor Valfli Titanyum Egzoz Sistemi',
    ],
    description:
      'V10 doğal emişli saf ses senfonisi. Tüm tekerleklerden çekiş, arka aks yönlendirme ve LDVI yapay zeka sürüş yönetim sistemiyle süper spor otomobil deneyimini yeniden tanımlayın.',
    isAvailable: true,
    isPopular: true,
    rating: 4.98,
    reviewCount: 68,
    location: 'Antalya, Lara VIP Terminal',
  },
  {
    brand: 'Aston Martin',
    model: 'Vantage',
    year: 2025,
    category: 'Spor',
    transmission: 'Otomatik',
    fuelType: 'Benzin',
    capacity: 2,
    tankOrBattery: '73 L',
    horsepower: 656,
    acceleration: '3.5s 0-100',
    topSpeed: '325 km/s',
    dailyPrice: 32000,
    discountPrice: 28900,
    features: [
      '4.0L Çift Turbo 665 PS V8',
      'Elektronik Arka Diferansiyel (E-Diff)',
      'Bowers & Wilkins 390W Ses Sistemi',
      'Köprü Deri El İşçiliği Döşeme',
      'Karbon Seramik Fren Paketi',
    ],
    description:
      'İngiliz aristokrasisinin vahşi yırtıcısı. 656 beygirlik çift turbolu motor, kusursuz 50:50 ağırlık dağılımı ve nefes kesen kaslı gövde tasarımı.',
    isAvailable: true,
    isPopular: false,
    rating: 4.93,
    reviewCount: 29,
    location: 'İzmir, Çeşme Marina',
  },
  {
    brand: 'BMW',
    model: 'M4 Competition',
    year: 2024,
    category: 'Spor',
    transmission: 'Otomatik',
    fuelType: 'Benzin',
    capacity: 4,
    tankOrBattery: '59 L',
    horsepower: 503,
    acceleration: '3.4s 0-100',
    topSpeed: '290 km/s',
    dailyPrice: 13500,
    discountPrice: 12000,
    features: [
      'M xDrive Akıllı Dört Çeker',
      'M Karbon Çanak Koltuklar',
      'Karbon Fiber Tavan Mimarisi',
      'Harman Kardon Surround Ses',
      'M Drift Analizörü ve Pist Modu',
    ],
    description:
      'Pist performansını günlük konforla harmanlayan safkan bir spor coupe. M TwinPower Turbo sıralı 6 silindirli motoru ve 503 beygir gücüyle adrenalin dolu bir sürüş deneyimi.',
    isAvailable: true,
    isPopular: true,
    rating: 4.94,
    reviewCount: 88,
    location: 'İstanbul, Kadıköy / Bağdat Caddesi',
  },
  {
    brand: 'Nissan',
    model: 'GT-R Nismo',
    year: 2024,
    category: 'Spor',
    transmission: 'Otomatik',
    fuelType: 'Benzin',
    capacity: 4,
    tankOrBattery: '74 L',
    horsepower: 600,
    acceleration: '2.9s 0-100',
    topSpeed: '330 km/s',
    dailyPrice: 19500,
    features: [
      'Çift Turbo El Yapımı VR38DETT V6',
      'ATTESA E-TS Dört Çeker Sistemi',
      'Brembo Karbon Seramik Frenler',
      'Recaro Karbon Yarış Koltukları',
      'Nismo Titanyum Egzos Sistemi',
    ],
    description:
      'Efsanevi Godzilla. Takumi ustaları tarafından tozsuz temiz odalarda el işçiliğiyle üretilen çift turbo V6 motor, ATTESA E-TS dört çeker çekiş gücü ve ödün vermeyen yarış aerodinamiği.',
    isAvailable: true,
    isPopular: false,
    rating: 4.95,
    reviewCount: 64,
    location: 'Ankara, Çankaya / Gaziosmanpaşa',
  },
  {
    brand: 'Audi',
    model: 'R8 V10 Performance',
    year: 2024,
    category: 'Spor',
    transmission: 'Otomatik',
    fuelType: 'Benzin',
    capacity: 2,
    tankOrBattery: '83 L',
    horsepower: 602,
    acceleration: '3.1s 0-100',
    topSpeed: '331 km/s',
    dailyPrice: 36000,
    discountPrice: 32500,
    features: [
      '5.2 Litre V10 FSI Atmosferik Güç Ünitesi',
      'Quattro Sürekli Dört Çeker Sistemi',
      'Bang & Olufsen 3D Ses Sistemi',
      'Lazer Destekli LED Farlar',
      'Karbon Fiber Yan Kanatlar (Sideblades)',
    ],
    description:
      'Göz alıcı hatlar ve saf atmosferik V10 kükremesi. Quattro çekiş gücü sayesinde yola yapışan sürüş dengesi ve havacılık kokpitlerini andıran dijital Audi Virtual Cockpit.',
    isAvailable: true,
    isPopular: true,
    rating: 4.96,
    reviewCount: 45,
    location: 'İstanbul, Beşiktaş / Bebek',
  },
  {
    brand: 'Mercedes-AMG',
    model: 'GT Coupe',
    year: 2025,
    category: 'Spor',
    transmission: 'Otomatik',
    fuelType: 'Benzin',
    capacity: 4,
    tankOrBattery: '70 L',
    horsepower: 577,
    acceleration: '3.2s 0-100',
    topSpeed: '315 km/s',
    dailyPrice: 26000,
    discountPrice: 23500,
    features: [
      'AMG 4.0L V8 Biturbo El Yapımı Motor',
      'AMG Performance 4MATIC+ Dört Çeker',
      'Aktif Arka Aks Yönlendirmesi',
      'AMG Ride Control Süspansiyon',
      'Burmester High-End 3D Surround Ses',
    ],
    description:
      'Afalterbach mühendisliğinin başyapıtı. Genişletilmiş gövde yapısı, 577 beygirlik V8 biturbo motoru ve akıllı tork dağılımı sağlayan AMG Performance 4MATIC+ çekiş sistemi.',
    isAvailable: true,
    isPopular: false,
    rating: 4.92,
    reviewCount: 37,
    location: 'İstanbul, Göktürk / Kemerburgaz',
  },
  {
    brand: 'Chevrolet',
    model: 'Corvette Z06',
    year: 2024,
    category: 'Spor',
    transmission: 'Otomatik',
    fuelType: 'Benzin',
    capacity: 2,
    tankOrBattery: '70 L',
    horsepower: 670,
    acceleration: '2.6s 0-100',
    topSpeed: '314 km/s',
    dailyPrice: 24000,
    features: [
      '5.5L LT6 Düz Kranklı Atmosferik V8 (8.600 Devir)',
      'Magnetic Selective Ride Control 4.0',
      'Bose Performance Series 14 Hoparlör',
      'Performans Veri Kaydedicisi (PDR)',
      'Çıkarılabilir Karbon Tavan Paneli',
    ],
    description:
      'Amerikan süper otomobil devrimi. Düz krank milline sahip 670 beygirlik atmosferik V8 motoruyla 8.600 devir çeviren, ortadan motorlu gerçek bir pist fatihi.',
    isAvailable: true,
    isPopular: false,
    rating: 4.91,
    reviewCount: 28,
    location: 'İzmir, Alsancak',
  },
  {
    brand: 'Toyota',
    model: 'GR Supra 3.0',
    year: 2024,
    category: 'Spor',
    transmission: 'Otomatik',
    fuelType: 'Benzin',
    capacity: 2,
    tankOrBattery: '52 L',
    horsepower: 382,
    acceleration: '3.9s 0-100',
    topSpeed: '250 km/s',
    dailyPrice: 8500,
    discountPrice: 7500,
    features: [
      '3.0 Litre Twin-Scroll Turbo Sıralı 6 Silindir',
      'Aktif Spor Diferansiyel',
      'Adaptif Değişken Süspansiyon (AVS)',
      'Brembo 4 Pistonlu Spor Fren Kaliperleri',
      'JBL 12 Hoparlörlü Premium Ses Sistemi',
    ],
    description:
      'Gazoo Racing ruhuyla geliştirilen efsanenin geri dönüşü. İdeal 50:50 ağırlık dengesi, yüksek torklu 6 silindirli turbo motoru ve çevik şasisiyle saf sürüş zevki.',
    isAvailable: true,
    isPopular: false,
    rating: 4.88,
    reviewCount: 35,
    location: 'Antalya, Konyaaltı',
  },

  // ==========================================
  // 2. ELEKTRİKLİ (NEXT-GEN EV & HIGH-PERFORMANCE)
  // ==========================================
  {
    brand: 'Porsche',
    model: 'Taycan 4S',
    year: 2025,
    category: 'Elektrikli',
    transmission: 'Tek Vites',
    fuelType: 'Elektrik',
    capacity: 4,
    tankOrBattery: '93.4 kWh',
    horsepower: 522,
    acceleration: '3.8s 0-100',
    topSpeed: '250 km/s',
    dailyPrice: 14500,
    discountPrice: 12900,
    features: [
      '800V Ultra Hızlı Şarj Mimarisi (22 dk %5-%80)',
      'Porsche InnoDrive Akıllı Otoyol Asistanı',
      'Panoramik Sabit Isı Yalıtımlı Cam Tavan',
      'Burmester 3D High-End Ses Sistemi',
      'FastPass NFC Dijital Mobil Anahtar',
    ],
    description:
      'Elektriğin saf gücüyle üst düzey grand-touring konforunun kusursuz birleşimi. 800V ultra hızlı mimarisi sayesinde yüksek hızlı DC istasyonlarda yalnızca 22 dakikada şarj olur.',
    isAvailable: true,
    isPopular: true,
    rating: 4.96,
    reviewCount: 112,
    location: 'İstanbul, Maslak Finans Merkezi',
  },
  {
    brand: 'Porsche',
    model: 'Taycan Turbo S',
    year: 2025,
    category: 'Elektrikli',
    transmission: 'Tek Vites',
    fuelType: 'Elektrik',
    capacity: 4,
    tankOrBattery: '93.4 kWh',
    horsepower: 750,
    acceleration: '2.6s 0-100',
    topSpeed: '260 km/s',
    dailyPrice: 22000,
    discountPrice: 19500,
    features: [
      'Launch Control ile 750 HP Aşırı Güç',
      'PCCB Seramik Kompozit Frenler',
      'Porsche Tork Vektörleme Plus (PTV+)',
      'Arka Aks Yönlendirmeli Havalı Süspansiyon',
      'Yolcu Multimedya Dokunmatik Ekranı',
    ],
    description:
      'Elektrikli mobilitede hiper otomobil performansı. Kalkış kontrolüyle 2.6 saniyede 100 km/s hıza ulaşan, yarış genlerine sahip dört kapılı elektrikli roket.',
    isAvailable: true,
    isPopular: true,
    rating: 4.99,
    reviewCount: 78,
    location: 'İstanbul, Havalimanı (IST) VIP Terminal',
  },
  {
    brand: 'Tesla',
    model: 'Model S Plaid',
    year: 2024,
    category: 'Elektrikli',
    transmission: 'Tek Vites',
    fuelType: 'Elektrik',
    capacity: 5,
    tankOrBattery: '100 kWh',
    horsepower: 1020,
    acceleration: '1.99s 0-100',
    topSpeed: '322 km/s',
    dailyPrice: 15500,
    discountPrice: 13900,
    features: [
      'Üç Motorlu Dört Çeker (1020 HP Karbon Rotor)',
      'Full Self-Driving (FSD Otonom Sürüş)',
      'Yoke Fütüristik Direksiyon Tasarımı',
      '10 Teraflops Oyun ve Multimedya Sistemi',
      'Isıtmalı ve Soğutmalı Ergonomik Koltuklar',
    ],
    description:
      'Geniş beş kişilik lüks bir sedanda hiper otomobil ivmelenmesi. Üç motorlu karbon sargılı mimarisiyle 2 saniyenin altında 0-100 km/s hızlanma ve kesintisiz Supercharger menzil özgürlüğü.',
    isAvailable: true,
    isPopular: true,
    rating: 4.97,
    reviewCount: 140,
    location: 'İzmir, Çeşme / Alaçatı',
  },
  {
    brand: 'Tesla',
    model: 'Model X Plaid',
    year: 2024,
    category: 'Elektrikli',
    transmission: 'Tek Vites',
    fuelType: 'Elektrik',
    capacity: 6,
    tankOrBattery: '100 kWh',
    horsepower: 1020,
    acceleration: '2.5s 0-100',
    topSpeed: '262 km/s',
    dailyPrice: 16500,
    discountPrice: 14800,
    features: [
      'Şahin Kanat (Falcon Wing) Otomatik Kapılar',
      '1020 HP Üç Elektrik Motoru',
      'HEPA Biyolojik Savunma Hava Filtresi',
      '6 Kişilik Özel Kaptan Koltuğu Düzeni',
      'Gelişmiş Adaptif Havalı Süspansiyon',
    ],
    description:
      'Dünyanın en hızlı hızlanan SUV modeli. İkonik şahin kanat kapıları, 1.020 beygir gücü ve 6 kişilik bağımsız VIP koltuk düzeniyle geleceğin aile konsepti.',
    isAvailable: true,
    isPopular: false,
    rating: 4.93,
    reviewCount: 52,
    location: 'İstanbul, Ataşehir / Batı Ataşehir',
  },
  {
    brand: 'Tesla',
    model: 'Model Y Long Range',
    year: 2024,
    category: 'Elektrikli',
    transmission: 'Tek Vites',
    fuelType: 'Elektrik',
    capacity: 5,
    tankOrBattery: '78 kWh',
    horsepower: 384,
    acceleration: '4.8s 0-100',
    topSpeed: '217 km/s',
    dailyPrice: 5800,
    discountPrice: 5100,
    features: [
      'Çift Motorlu Akıllı Dört Çeker (AWD)',
      '533 km WLTP Menzil Kapasitesi',
      '2.100+ Litre Dev Bagaj Hacmi',
      'Geniş Panoramik Cam Tavan',
      'Tesla Supercharger Ağı Tam Uyumluluk',
    ],
    description:
      'Yüksek verimlilik, geniş iç hacim ve üstün güvenlik. Uzun yolculuklar için ideal 533 km menzili, yüksek oturma pozisyonu ve minimalist ferah kabiniyle konforlu bir elektrikli SUV.',
    isAvailable: true,
    isPopular: true,
    rating: 4.9,
    reviewCount: 165,
    location: 'Bursa, Nilüfer / Balat',
  },
  {
    brand: 'Tesla',
    model: 'Model 3 Performance',
    year: 2024,
    category: 'Elektrikli',
    transmission: 'Tek Vites',
    fuelType: 'Elektrik',
    capacity: 5,
    tankOrBattery: '82 kWh',
    horsepower: 510,
    acceleration: '3.1s 0-100',
    topSpeed: '262 km/s',
    dailyPrice: 6200,
    discountPrice: 5500,
    features: [
      'Pist Modu V3 (Track Mode)',
      'Yeni Nesil Spor Destekli Koltuklar',
      'Adaptif Amortisör Sistemi',
      'Akustik Akıllı Çift Cam Yalıtımı',
      'Karbon Fiber Arka Spoiler',
    ],
    description:
      'Yenilenen Highland gövde tasarımında 510 beygirlik saf elektrikli çeviklik. 3.1 saniyelik 0-100 ivmelenmesi, yenilenen sessiz kabini ve dinamik pist modu.',
    isAvailable: true,
    isPopular: false,
    rating: 4.89,
    reviewCount: 76,
    location: 'Ankara, Çukurambar',
  },
  {
    brand: 'BMW',
    model: 'i7 eDrive50',
    year: 2025,
    category: 'Elektrikli',
    transmission: 'Tek Vites',
    fuelType: 'Elektrik',
    capacity: 5,
    tankOrBattery: '101.7 kWh',
    horsepower: 536,
    acceleration: '4.5s 0-100',
    topSpeed: '205 km/s',
    dailyPrice: 17500,
    discountPrice: 15500,
    features: [
      '31 inç 8K Sinema Ekranı (BMW Theatre Screen)',
      'Executive Lounge Masajlı Arka Koltuklar',
      'Bowers & Wilkins Diamond 4D Surround Ses',
      'Otomatik Açılan Kapanan Sensörlü Kapılar',
      'BMW Interaction Bar Kristal Işık Paneli',
    ],
    description:
      'Yenilikçi üst düzey lüksün yeni standardı. Arka kabinde tavandan inen 31 inç 8K sinema ekranı, fısıltı sessizliğinde elektrikli sürüş ve birinci sınıf yönetici konforu.',
    isAvailable: true,
    isPopular: true,
    rating: 4.95,
    reviewCount: 67,
    location: 'Ankara, Çankaya / Gaziosmanpaşa',
  },
  {
    brand: 'BMW',
    model: 'i4 M50',
    year: 2024,
    category: 'Elektrikli',
    transmission: 'Tek Vites',
    fuelType: 'Elektrik',
    capacity: 5,
    tankOrBattery: '83.9 kWh',
    horsepower: 536,
    acceleration: '3.7s 0-100',
    topSpeed: '225 km/s',
    dailyPrice: 8500,
    discountPrice: 7600,
    features: [
      'Çift Elektrikli M Motor Mimarisi',
      'M Adaptif Şasi ve Değişken Spor Direksiyon',
      'BMW Kavisli Ekran (iDrive 8.5)',
      'Harman Kardon Ses Sistemi',
      'Hans Zimmer İmzalı M İkonik Sesler',
    ],
    description:
      'BMW M ruhunun elektrikle buluşması. 536 beygir güç, dört çeker çekiş kabiliyeti, düşük ağırlık merkezi ve Hans Zimmer tarafından bestelenen büyüleyici hızlanma sesleri.',
    isAvailable: true,
    isPopular: false,
    rating: 4.91,
    reviewCount: 54,
    location: 'İstanbul, Kadıköy / Bağdat Caddesi',
  },
  {
    brand: 'Audi',
    model: 'RS e-tron GT',
    year: 2024,
    category: 'Elektrikli',
    transmission: 'Tek Vites',
    fuelType: 'Elektrik',
    capacity: 5,
    tankOrBattery: '93.4 kWh',
    horsepower: 637,
    acceleration: '3.1s 0-100',
    topSpeed: '250 km/s',
    dailyPrice: 16000,
    features: [
      'Quattro Elektrikli Akıllı Dört Çeker',
      'Karbon Fiber Tavan ve Gövde Detayları',
      'Bang & Olufsen 3D Premium Ses Sistemi',
      'e-torque Vectoring Plus Tork Dağılımı',
      'Matrix LED Lazer Farlar',
    ],
    description:
      'Nefes kesici grand tourer oranları ve çift elektrik motorlu roket ivmelenmesi. Göz alıcı aerodinamik tasarımı yüksek Alman mühendisliğiyle harmanlayan fütüristik bir sanat eseri.',
    isAvailable: true,
    isPopular: true,
    rating: 4.93,
    reviewCount: 49,
    location: 'Bursa, Nilüfer / Balat',
  },
  {
    brand: 'Lucid',
    model: 'Air Sapphire',
    year: 2025,
    category: 'Elektrikli',
    transmission: 'Tek Vites',
    fuelType: 'Elektrik',
    capacity: 5,
    tankOrBattery: '118 kWh',
    horsepower: 1234,
    acceleration: '1.89s 0-100',
    topSpeed: '330 km/s',
    dailyPrice: 28000,
    discountPrice: 25000,
    features: [
      'Üç Motorlu 1.234 HP Güç Ünitesi',
      'Karbon-Seramik Yarış Frenleri',
      '34 inç Cam Kokpit Kavisli 5K Ekran',
      'Surreal Sound Pro (21 Hoparlör)',
      'LiDAR Destekli DreamDrive Pro Otonom Sürüş',
    ],
    description:
      'Dünyanın en güçlü elektrikli lüks süper-sedanı. 1.200 beygiri aşan üç motorlu güç ünitesi, 1.89 saniyelik 0-100 ivmelenmesi ve havacılık standartlarında fütüristik iç yaşam alanı.',
    isAvailable: true,
    isPopular: false,
    rating: 4.98,
    reviewCount: 41,
    location: 'İstanbul, Kadıköy / Bağdat Caddesi',
  },
  {
    brand: 'Mercedes-Benz',
    model: 'EQS 580 4MATIC',
    year: 2024,
    category: 'Elektrikli',
    transmission: 'Tek Vites',
    fuelType: 'Elektrik',
    capacity: 5,
    tankOrBattery: '107.8 kWh',
    horsepower: 516,
    acceleration: '4.1s 0-100',
    topSpeed: '210 km/s',
    dailyPrice: 15000,
    discountPrice: 13500,
    features: [
      '56 inç MBUX Hyperscreen Tek Parça Cam Ekran',
      'Arka Aks 10 Derece Yönlendirme Sistemi',
      'Airmatic Havalı Süspansiyon Paketi',
      'Burmester 3D Surround Ses & Dolbly Atmos',
      'HEPA Filtreli İç Hava Temizleme Sistemi',
    ],
    description:
      'Elektrikli lüksün amiral gemisi. Ön konsolu boydan boya kaplayan 56 inçlik yekpare Hyperscreen ekranı, 10 derece dönebilen arka aksı ve ipeksi pürüzsüzlükte havalı süspansiyonu.',
    isAvailable: true,
    isPopular: false,
    rating: 4.92,
    reviewCount: 39,
    location: 'İstanbul, Beşiktaş',
  },

  // ==========================================
  // 3. SUV (LUXURY, OFF-ROAD & ULTRA PERFORMANCE)
  // ==========================================
  {
    brand: 'Mercedes-AMG',
    model: 'G 63',
    year: 2025,
    category: 'SUV',
    transmission: 'Otomatik',
    fuelType: 'Benzin',
    capacity: 5,
    tankOrBattery: '100 L',
    horsepower: 577,
    acceleration: '4.5s 0-100',
    topSpeed: '240 km/s',
    dailyPrice: 26500,
    discountPrice: 23500,
    features: [
      'AMG 4.0L V8 Çift Turbo El Yapımı Motor',
      'Üç Mekanik Diferansiyel Kilidi (%100 Kilitli)',
      'Yandan Çıkışlı AMG Spor Egzoz Sistemi',
      'Burmester Surround Ses Sistemi',
      'Özel Baklava Dikişli Nappa Deri Döşeme',
    ],
    description:
      'Otomotiv dünyasının rakipsiz lüks ikonu. V8 biturbo homurtusu, heybetli yol duruşu, üç kilitli diferansiyel sistemi ve el işçiliği Nappa deri iç mekan tasarımı.',
    isAvailable: true,
    isPopular: true,
    rating: 4.99,
    reviewCount: 148,
    location: 'İstanbul, Göktürk / Kemerburgaz',
  },
  {
    brand: 'Range Rover',
    model: 'Autobiography',
    year: 2025,
    category: 'SUV',
    transmission: 'Otomatik',
    fuelType: 'Hibrit',
    capacity: 7,
    tankOrBattery: '90 L',
    horsepower: 523,
    acceleration: '4.6s 0-100',
    topSpeed: '250 km/s',
    dailyPrice: 21500,
    discountPrice: 19000,
    features: [
      'Dört Tekerden Yönlendirme (All-Wheel Steering)',
      'Meridian Signature Ses Sistemi (35 Hoparlör)',
      'Executive Class Comfort-Plus Koltuklar',
      'Terrain Response 2 Akıllı Arazi Sistemi',
      'Elektronik Havalı Süspansiyon & Aktif Yalpa Kontrolü',
    ],
    description:
      'Eşsiz aristokratik zarafet ve heybetli arazi hakimiyeti. Yedi kişilik cömert yönetici koltukları, sınıfının en sessiz kabin mimarisi ve her yol koşuluna anında uyarlanan akıllı şasi.',
    isAvailable: true,
    isPopular: true,
    rating: 4.97,
    reviewCount: 104,
    location: 'Muğla, Bodrum Marina / Yalıkavak',
  },
  {
    brand: 'Range Rover',
    model: 'Sport Dynamic SE',
    year: 2024,
    category: 'SUV',
    transmission: 'Otomatik',
    fuelType: 'Hibrit',
    capacity: 5,
    tankOrBattery: '86 L',
    horsepower: 395,
    acceleration: '5.4s 0-100',
    topSpeed: '242 km/s',
    dailyPrice: 13500,
    discountPrice: 12000,
    features: [
      'Dinamik Havalı Süspansiyon Sistemi',
      'Pivi Pro 13.1 inç Dokunmatik Bilgi-Eğlence',
      'Meridian 3D Surround Ses Sistemi',
      '360 Derece 3D Çevre Görüş Kamerası',
      'Pixel LED Farlar & Dinamik Sinyaller',
    ],
    description:
      'Sportif dinamizm ve kusursuz İngiliz lüksü. Yüksek oturma pozisyonu, her yol koşuluna meydan okuyan havalı süspansiyonu ve aerodinamik sportif gövde hatları.',
    isAvailable: true,
    isPopular: false,
    rating: 4.91,
    reviewCount: 63,
    location: 'Antalya, Lara',
  },
  {
    brand: 'Cadillac',
    model: 'Escalade-V',
    year: 2024,
    category: 'SUV',
    transmission: 'Otomatik',
    fuelType: 'Benzin',
    capacity: 7,
    tankOrBattery: '91 L',
    horsepower: 682,
    acceleration: '4.4s 0-100',
    topSpeed: '200 km/s',
    dailyPrice: 24000,
    discountPrice: 21500,
    features: [
      'Süperşarjlı 6.2L V8 Motor (682 HP)',
      'AKG Studio Reference 36 Hoparlörlü Ses Sistemi',
      'Kavisli 38 inç OLED Kokpit Ekranı',
      'Magnetic Ride Control 4.0 Süspansiyon',
      'Super Cruise Otonom Sürüş Asistanı',
    ],
    description:
      'Amerikan lüksünün ve saf kas gücünün zirvesi. 6.2 litre süperşarjlı dev V8 motor, 38 inç kavisli kavisli OLED ekran ve 36 hoparlörlü stüdyo kalitesinde ses sistemi.',
    isAvailable: true,
    isPopular: false,
    rating: 4.9,
    reviewCount: 46,
    location: 'İstanbul, Ataşehir / Batı Ataşehir',
  },
  {
    brand: 'Lamborghini',
    model: 'Urus Performante',
    year: 2024,
    category: 'SUV',
    transmission: 'Otomatik',
    fuelType: 'Benzin',
    capacity: 5,
    tankOrBattery: '85 L',
    horsepower: 657,
    acceleration: '3.3s 0-100',
    topSpeed: '306 km/s',
    dailyPrice: 42000,
    discountPrice: 37500,
    features: [
      '4.0 Litre Twin-Turbo V8 Güç Ünitesi',
      'Akrapovic Titanyum Yarış Egzoz Sistemi',
      'Karbon Fiber Kaput ve Genişletilmiş Çamurluklar',
      'Bang & Olufsen 3D Advanced Ses Sistemi',
      'Rally Sürüş Modu ve Alçaltılmış Çelik Yaylar',
    ],
    description:
      'Süper spor otomobil ruhuna sahip ilk Super-SUV. 657 beygir gücü, Akrapovic titanyum egzoz kükremesi ve pist odaklı aerodinamik karbon gövde elemanları.',
    isAvailable: true,
    isPopular: true,
    rating: 4.98,
    reviewCount: 82,
    location: 'İstanbul, İstinyePark VIP',
  },
  {
    brand: 'Porsche',
    model: 'Cayenne Turbo GT',
    year: 2024,
    category: 'SUV',
    transmission: 'Otomatik',
    fuelType: 'Benzin',
    capacity: 5,
    tankOrBattery: '90 L',
    horsepower: 650,
    acceleration: '3.1s 0-100',
    topSpeed: '305 km/s',
    dailyPrice: 25000,
    discountPrice: 22000,
    features: [
      '4.0L Çift Turbo V8 Yüksek Performans Motor',
      'Titanyum Merkezi Çıkışlı Spor Egzoz',
      'PCCB Seramik Kompozit Frenler',
      'Aktif Karbon Tavan ve Karbon Arka Kanat',
      'Alcantara GT Spor Direksiyon ve Koltuklar',
    ],
    description:
      'Nürburgring rekoru kıran SUV mimarisi. 3.1 saniyelik olağanüstü ivmelenme, titanyum egzoz sistemi ve virajlarda fizik kurallarına meydan okuyan aktif stabilizasyon.',
    isAvailable: true,
    isPopular: false,
    rating: 4.95,
    reviewCount: 51,
    location: 'İstanbul, Bebek',
  },
  {
    brand: 'Porsche',
    model: 'Macan GTS',
    year: 2024,
    category: 'SUV',
    transmission: 'PDK',
    fuelType: 'Benzin',
    capacity: 5,
    tankOrBattery: '75 L',
    horsepower: 434,
    acceleration: '4.3s 0-100',
    topSpeed: '272 km/s',
    dailyPrice: 11500,
    discountPrice: 10200,
    features: [
      '2.9 Litre V6 Çift Turbo Motor',
      'GTS Özel Alçaltılmış Havalı Süspansiyon (-10mm)',
      'Sport Chrono Paketi',
      'Bose Surround Ses Sistemi',
      '21 inç RS Spyder Tasarım Parlak Siyah Jantlar',
    ],
    description:
      'Kompakt lüks SUV segmentinin en dinamik temsilcisi. 434 beygirlik çift turbo V6 motor, spor egzoz kükremesi ve günlük kullanıma kusursuz uyum sağlayan çevik şasi.',
    isAvailable: true,
    isPopular: false,
    rating: 4.89,
    reviewCount: 44,
    location: 'İzmir, Alsancak',
  },
  {
    brand: 'BMW',
    model: 'X7 M60i xDrive',
    year: 2025,
    category: 'SUV',
    transmission: 'Otomatik',
    fuelType: 'Hibrit',
    capacity: 7,
    tankOrBattery: '83 L',
    horsepower: 523,
    acceleration: '4.5s 0-100',
    topSpeed: '250 km/s',
    dailyPrice: 17500,
    discountPrice: 15500,
    features: [
      '4.4L TwinPower Turbo V8 Mild-Hybrid Motor',
      'Sky Lounge Panoramik Cam Tavan (LED Işıklı)',
      'Bowers & Wilkins Diamond 3D Ses Sistemi',
      'Executive Drive Pro Aktif Şasi Kontrolü',
      'Merino Deri Havalandırmalı Koltuklar',
    ],
    description:
      'Yedi kişilik lüksün en görkemli hali. Aydınlatmalı Sky Lounge cam tavanı, 523 beygirlik V8 gücü ve birinci sınıf yönetici koltuklarıyla konfor dolu uzun yolculuklar.',
    isAvailable: true,
    isPopular: true,
    rating: 4.94,
    reviewCount: 71,
    location: 'Ankara, Çankaya',
  },
  {
    brand: 'Audi',
    model: 'RS Q8',
    year: 2024,
    category: 'SUV',
    transmission: 'Otomatik',
    fuelType: 'Hibrit',
    capacity: 5,
    tankOrBattery: '85 L',
    horsepower: 591,
    acceleration: '3.7s 0-100',
    topSpeed: '305 km/s',
    dailyPrice: 18500,
    discountPrice: 16500,
    features: [
      '4.0L Çift Turbo V8 Motor (591 HP)',
      'Quattro Spor Diferansiyel ve Dört Teker Yönlendirme',
      'RS Özel Uyarlanabilir Havalı Süspansiyon',
      'Bang & Olufsen Gelişmiş 3D Ses',
      '23 inç 5 Y Kollu Titanyum Jantlar',
    ],
    description:
      'Geniş coupe-SUV siluetinde gizlenmiş süper spor canavar. 591 beygirlik V8 gücü, elektro-mekanik aktif yalpa dengeleme sistemi ve göz alıcı RS tasarım detayları.',
    isAvailable: true,
    isPopular: false,
    rating: 4.93,
    reviewCount: 57,
    location: 'İstanbul, Maslak',
  },
  {
    brand: 'Bentley',
    model: 'Bentayga Azure',
    year: 2024,
    category: 'SUV',
    transmission: 'Otomatik',
    fuelType: 'Benzin',
    capacity: 5,
    tankOrBattery: '85 L',
    horsepower: 542,
    acceleration: '4.4s 0-100',
    topSpeed: '290 km/s',
    dailyPrice: 38000,
    discountPrice: 34000,
    features: [
      '4.0 Litre Twin-Turbo V8 Motor',
      'Bentley Dynamic Ride 48V Aktif Yalpa Kontrolü',
      'Naim for Bentley 1.780W Ses Sistemi',
      'El Dikimi Elmas Desenli Deri Döşeme',
      'Isıtmalı, Havalandırmalı ve Masajlı Koltuklar',
    ],
    description:
      'İngiliz el işçiliğinin lüks SUV ile buluşması. Crewe fabrikasında el yapımı ahşap kaplamalar, Naim 1.780 wattlık müzik deneyimi ve sarsıntısız ipeksi sürüş hissi.',
    isAvailable: true,
    isPopular: false,
    rating: 4.97,
    reviewCount: 33,
    location: 'Muğla, Bodrum Marina',
  },
  {
    brand: 'Volvo',
    model: 'XC90 Recharge Ultimate',
    year: 2024,
    category: 'SUV',
    transmission: 'Otomatik',
    fuelType: 'Hibrit',
    capacity: 7,
    tankOrBattery: '71 L',
    horsepower: 455,
    acceleration: '5.0s 0-100',
    topSpeed: '180 km/s',
    dailyPrice: 8900,
    discountPrice: 7900,
    features: [
      'Plug-in Hybrid 455 HP Güç & Dört Çeker',
      'Bowers & Wilkins Konser Salonu Ses Sistemi',
      'İsveç Orrefors Kristal Vites Kolu',
      'Gelişmiş Hava Temizleme Sistemi (PM 2.5)',
      'Pilot Assist Yarı Otonom Sürüş Asistanı',
    ],
    description:
      'İskandinav zarafeti, tavizsiz güvenlik ve 7 kişilik ferahlık. Bowers & Wilkins Göteborg Konser Salonu akustiği, Orrefors kristal vites topuzu ve sessiz hibrit sürüş.',
    isAvailable: true,
    isPopular: false,
    rating: 4.88,
    reviewCount: 69,
    location: 'İstanbul, Levent',
  },
  {
    brand: 'Rolls-Royce',
    model: 'Cullinan',
    year: 2024,
    category: 'SUV',
    transmission: 'Otomatik',
    fuelType: 'Benzin',
    capacity: 5,
    tankOrBattery: '100 L',
    horsepower: 563,
    acceleration: '5.1s 0-100',
    topSpeed: '250 km/s',
    dailyPrice: 58000,
    discountPrice: 52000,
    features: [
      '6.75 Litre Çift Turbo V12 Efsanevi Motor',
      'Sihirli Halı Sürüşü (Magic Carpet Ride) Süspansiyon',
      'Ters Açılan Karşılama Kapıları (Coach Doors)',
      'Bespoke Starlight Fiber-Optik Yıldızlı Tavan',
      'Arka Kabin Şampanya Soğutucu ve Kristal Kadehler',
    ],
    description:
      'Lüksün mutlak zirvesi. 6.75 litrelik V12 motorun sessiz kudreti, ters açılan ikonik koç kapıları, yıldızlı tavanı ve yoldaki pürüzleri tamamen yok eden sihirli süspansiyonu.',
    isAvailable: true,
    isPopular: true,
    rating: 5.0,
    reviewCount: 38,
    location: 'İstanbul, Bosphorus VIP',
  },

  // ==========================================
  // 4. SEDAN (EXECUTIVE & ULTRA-LUXURY SALOONS)
  // ==========================================
  {
    brand: 'Mercedes-Benz',
    model: 'S 580 4MATIC',
    year: 2024,
    category: 'Sedan',
    transmission: 'Otomatik',
    fuelType: 'Hibrit',
    capacity: 5,
    tankOrBattery: '76 L',
    horsepower: 496,
    acceleration: '4.4s 0-100',
    topSpeed: '250 km/s',
    dailyPrice: 18500,
    discountPrice: 16500,
    features: [
      'Aktif Ambiyans Aydınlatması (64 Renk)',
      'E-Active Body Control Havalı Süspansiyon',
      'Isıtmalı Kol Dayama ve Sıcak Taş Masajlı Koltuklar',
      'Artırılmış Gerçeklikli Head-Up Display (AR-HUD)',
      '4MATIC Akıllı Sürekli Dört Çeker',
    ],
    description:
      'Modern lüks yönetici ulaşımının tartışmasız zirvesi. Eşsiz akustik ses yalıtımı, birinci sınıf arka koltuk masaj paketleri ve ipeksi pürüzsüzlükte Airmatic havalı süspansiyon konforu.',
    isAvailable: true,
    isPopular: true,
    rating: 4.97,
    reviewCount: 92,
    location: 'İstanbul, Nişantaşı / Şişli',
  },
  {
    brand: 'BMW',
    model: 'M8 Competition Gran Coupe',
    year: 2024,
    category: 'Sedan',
    transmission: 'Otomatik',
    fuelType: 'Benzin',
    capacity: 5,
    tankOrBattery: '68 L',
    horsepower: 617,
    acceleration: '3.0s 0-100',
    topSpeed: '305 km/s',
    dailyPrice: 19000,
    features: [
      '4.4 Litre TwinPower Turbo V8 Motor',
      'Arkadan İtiş Modlu M xDrive Dört Çeker',
      'M Karbon-Seramik Fren Sistemi',
      'Bowers & Wilkins Diamond Surround Ses',
      'BMW Live Cockpit Professional',
    ],
    description:
      'Göz alıcı dört kapılı bir siluette gizlenmiş süper spor otomobil gücü. 617 beygirlik çift turbolu V8 motor ve istendiğinde saf arkadan itiş moduna geçebilen M xDrive çekiş sistemi.',
    isAvailable: true,
    isPopular: false,
    rating: 4.93,
    reviewCount: 58,
    location: 'İzmir, Alsancak / Kordon',
  },
  {
    brand: 'BMW',
    model: '740i xDrive Excellence',
    year: 2024,
    category: 'Sedan',
    transmission: 'Otomatik',
    fuelType: 'Hibrit',
    capacity: 5,
    tankOrBattery: '74 L',
    horsepower: 375,
    acceleration: '5.1s 0-100',
    topSpeed: '250 km/s',
    dailyPrice: 14500,
    discountPrice: 13000,
    features: [
      'BMW Kristal Ön Farlar ve Aydınlatmalı Böbrek Izgara',
      'Kapı İçlerine Entegre Dokunmatik Kumanda Ekranları',
      'Panoramik Sky Lounge Cam Tavan',
      'Bowers & Wilkins Surround Ses Sistemi',
      'Yönetici Arka Koltuk Konfor Paketi',
    ],
    description:
      'Makam otomobili kavramını fütüristik teknolojiyle buluşturan yeni 7 Serisi. Arka kapılardaki akıllı dokunmatik ekranlar, kristal kokpit detayları ve benzersiz seyahat konforu.',
    isAvailable: true,
    isPopular: false,
    rating: 4.91,
    reviewCount: 47,
    location: 'Ankara, Gaziosmanpaşa',
  },
  {
    brand: 'Audi',
    model: 'RS7 Sportback Performance',
    year: 2024,
    category: 'Sedan',
    transmission: 'Otomatik',
    fuelType: 'Hibrit',
    capacity: 5,
    tankOrBattery: '73 L',
    horsepower: 621,
    acceleration: '3.3s 0-100',
    topSpeed: '305 km/s',
    dailyPrice: 18000,
    discountPrice: 16000,
    features: [
      '4.0L Çift Turbo V8 (621 HP)',
      'Quattro Dinamik Dört Teker Yönlendirmesi',
      'RS Spor Süspansiyon Plus (Dynamic Ride Control)',
      'Bang & Olufsen Gelişmiş 3D Ses Sistemi',
      'HD Matrix LED Lazer Farlar',
    ],
    description:
      'Akıcı sportback tavan çizgisi ve yarış pistinden fırlamış 621 beygirlik V8 motor. Geniş liftback bagajı ile pratikliği süper spor sürüş dinamikleriyle buluşturan efsane.',
    isAvailable: true,
    isPopular: true,
    rating: 4.95,
    reviewCount: 65,
    location: 'İstanbul, Beşiktaş',
  },
  {
    brand: 'Bentley',
    model: 'Continental GT V8',
    year: 2024,
    category: 'Sedan',
    transmission: 'Otomatik',
    fuelType: 'Benzin',
    capacity: 4,
    tankOrBattery: '90 L',
    horsepower: 542,
    acceleration: '3.9s 0-100',
    topSpeed: '318 km/s',
    dailyPrice: 34000,
    discountPrice: 30500,
    features: [
      '4.0 Litre Twin-Turbo V8 Motor',
      'Bentley Dönen Gösterge Paneli (Üç Taraflı Ekran)',
      'Mulliner Sürüş Paketi ve Karbon Detaylar',
      'Naim for Bentley Üst Düzey Ses Sistemi',
      'Hava Yastıklı Çift Cam Akustik Yalıtım',
    ],
    description:
      'Kıtalararası seyahatlerin efsanevi Grand Tourer modeli. Dönen üç yönlü konsol ekranı, el işçiliği deri döşemeleri ve 318 km/s son hıza ulaştıran çift turbolu V8 motor.',
    isAvailable: true,
    isPopular: false,
    rating: 4.96,
    reviewCount: 39,
    location: 'Muğla, Bodrum Yalıkavak',
  },
  {
    brand: 'Rolls-Royce',
    model: 'Ghost Extended',
    year: 2024,
    category: 'Sedan',
    transmission: 'Otomatik',
    fuelType: 'Benzin',
    capacity: 5,
    tankOrBattery: '82 L',
    horsepower: 563,
    acceleration: '4.7s 0-100',
    topSpeed: '250 km/s',
    dailyPrice: 55000,
    features: [
      '6.75 Litre V12 Twin-Turbo Motor',
      'Planar Süspansiyon Sistemi (Dünyada İlk Ön Salıncak Amortisörü)',
      'Aydınlatmalı Ön Fascia ve 850+ Yıldızlı Yolcu Paneli',
      'Elektrikli Vakumlu Kendiliğinden Kapanan Kapılar',
      'Arka Kabin Bağımsız Eğlence Ekranları',
    ],
    description:
      'Kişiselleştirilmiş lüksün saf mimarisi. Uzatılmış dingil mesafesiyle uçsuz bucaksız arka diz mesafesi, 100 kg ses yalıtım malzemesiyle sağlanan mutlak kütüphane sessizliği.',
    isAvailable: true,
    isPopular: false,
    rating: 4.99,
    reviewCount: 26,
    location: 'İstanbul, Çırağan VIP',
  },
  {
    brand: 'Maserati',
    model: 'Ghibli Trofeo',
    year: 2024,
    category: 'Sedan',
    transmission: 'Otomatik',
    fuelType: 'Benzin',
    capacity: 5,
    tankOrBattery: '80 L',
    horsepower: 572,
    acceleration: '4.0s 0-100',
    topSpeed: '326 km/s',
    dailyPrice: 15500,
    discountPrice: 13800,
    features: [
      'Ferrari Tarafından Üretilen 3.8L Twin Turbo V8',
      'Corsa Pist Sürüş Modu ve Kalkış Kontrolü',
      'Pieno Fiore Doğal Deri Döşeme',
      'Bowers & Wilkins 1.280W Ses Sistemi',
      'Karbon Fiber Dış Gövde Detayları',
    ],
    description:
      'Ferrari üretimi 580 beygirlik V8 motorun hayat verdiği İtalyan rüyası. 326 km/s maksimum hızı, büyüleyici egzoz melodisi ve el yapımı Pieno Fiore deri kabini.',
    isAvailable: true,
    isPopular: false,
    rating: 4.9,
    reviewCount: 42,
    location: 'İzmir, Çeşme',
  },
  {
    brand: 'Mercedes-Benz',
    model: 'E 300 4MATIC AMG',
    year: 2024,
    category: 'Sedan',
    transmission: 'Otomatik',
    fuelType: 'Hibrit',
    capacity: 5,
    tankOrBattery: '66 L',
    horsepower: 255,
    acceleration: '6.0s 0-100',
    topSpeed: '250 km/s',
    dailyPrice: 7800,
    discountPrice: 6900,
    features: [
      'MBUX Superscreen Ön Konsol Ekranı',
      'Burmester 4D Surround Ses Sistemi',
      'AMG Dış ve İç Tasarım Konsepti',
      'Aktif Şerit Takip ve Kör Nokta Asistanı',
      'Dijital Işık Teknolojili LED Farlar',
    ],
    description:
      'İş dünyasının en çok tercih edilen yönetici sedanı. Yeni nesil Superscreen konsolu, sessiz hibrit motoru ve kusursuz güvenlik donanımlarıyla kusursuz bir kurumsal konfor.',
    isAvailable: true,
    isPopular: true,
    rating: 4.91,
    reviewCount: 98,
    location: 'İstanbul, Sabiha Gökçen (SAW)',
  },

  // ==========================================
  // 5. HATCHBACK (HOT HATCH & PREMIUM COMPACT)
  // ==========================================
  {
    brand: 'Mercedes-AMG',
    model: 'A 45 S 4MATIC+',
    year: 2024,
    category: 'Hatchback',
    transmission: 'Otomatik',
    fuelType: 'Benzin',
    capacity: 5,
    tankOrBattery: '51 L',
    horsepower: 416,
    acceleration: '3.9s 0-100',
    topSpeed: '270 km/s',
    dailyPrice: 7200,
    discountPrice: 6400,
    features: [
      'Dünyanın En Güçlü Seri Üretim 2.0L Turbo Motoru (M139)',
      'AMG Tork Kontrollü Drift Modu',
      'AMG Performance Yarış Koltukları',
      'Burmester Surround Ses Sistemi',
      'Aerodinamik Paket (Büyük Arka Kanat ve Ön Kanatçıklar)',
    ],
    description:
      'Kompakt gövdede 421 beygirlik roket. Dünyanın en güçlü 2.0 litrelik 4 silindirli turbo motoru, tork vektörlemeli drift modu ve sokakları yarış pistine çeviren çeviklik.',
    isAvailable: true,
    isPopular: true,
    rating: 4.93,
    reviewCount: 82,
    location: 'İstanbul, Kadıköy',
  },
  {
    brand: 'Audi',
    model: 'RS3 Sportback',
    year: 2024,
    category: 'Hatchback',
    transmission: 'Otomatik',
    fuelType: 'Benzin',
    capacity: 5,
    tankOrBattery: '55 L',
    horsepower: 394,
    acceleration: '3.6s 0-100',
    topSpeed: '290 km/s',
    dailyPrice: 6900,
    discountPrice: 6100,
    features: [
      '2.5 Litre Efsanevi 5 Silindirli Turbo Motor (1-2-4-5-3 Ateşleme)',
      'RS Torque Splitter Arka Aks Tork Dağıtıcısı',
      'Bang & Olufsen 3D Premium Ses',
      'Matrix LED Farlar ve RS Damalı Bayrak Işık İmzası',
      'RS Egzoz Sistemi (Ayarlanabilir Flaplı)',
    ],
    description:
      'Ödüllü 5 silindirli turbo motorun eşsiz homurtusu. RS Torque Splitter sayesinde arkadan itiş hissi veren tork dağıtımı ve 3.6 saniyelik 0-100 km/s roket ivmelenmesi.',
    isAvailable: true,
    isPopular: true,
    rating: 4.95,
    reviewCount: 77,
    location: 'Bursa, Nilüfer',
  },
  {
    brand: 'Volkswagen',
    model: 'Golf R 20 Years',
    year: 2024,
    category: 'Hatchback',
    transmission: 'Otomatik',
    fuelType: 'Benzin',
    capacity: 5,
    tankOrBattery: '50 L',
    horsepower: 328,
    acceleration: '4.6s 0-100',
    topSpeed: '270 km/s',
    dailyPrice: 5400,
    discountPrice: 4800,
    features: [
      'R-Performance Tork Vektörleme Dört Çeker',
      'Özel Nürburgring ve Drift Sürüş Modları',
      'Akrapovic Titanyum Arka Egzoz Sistemi',
      'Harman Kardon 480W Ses Sistemi',
      'Nappa Deri Mavi Dikişli R Koltuklar',
    ],
    description:
      'Hot hatch sınıfının referans noktası. 333 beygir güç, Akrapovic titanyum egzoz sistemi ve Nürburgring modunda optimize edilen şasi dinamikleriyle saf eğlence.',
    isAvailable: true,
    isPopular: false,
    rating: 4.9,
    reviewCount: 61,
    location: 'Antalya, Muratpaşa',
  },
  {
    brand: 'BMW',
    model: 'M135i xDrive',
    year: 2024,
    category: 'Hatchback',
    transmission: 'Otomatik',
    fuelType: 'Benzin',
    capacity: 5,
    tankOrBattery: '50 L',
    horsepower: 302,
    acceleration: '4.7s 0-100',
    topSpeed: '250 km/s',
    dailyPrice: 5100,
    features: [
      '2.0L M TwinPower Turbo 4 Silindirli Motor',
      'xDrive Akıllı Dört Çeker ve Torsen Kilitli Diferansiyel',
      'M Spor Frenler ve Kırmızı Kaliperler',
      'Harman Kardon Ses Sistemi',
      'M Spor Aerodinamik Gövde Kiti',
    ],
    description:
      'Şehirde kompakt, virajda keskin. Torsen mekanik sınırlı kaydırmalı diferansiyeli ve akıllı dört çeker sistemiyle her mevsimde maksimum yol tutuş garantisi.',
    isAvailable: true,
    isPopular: false,
    rating: 4.87,
    reviewCount: 45,
    location: 'Ankara, Çankaya',
  },
  {
    brand: 'Mini',
    model: 'John Cooper Works',
    year: 2024,
    category: 'Hatchback',
    transmission: 'Otomatik',
    fuelType: 'Benzin',
    capacity: 4,
    tankOrBattery: '44 L',
    horsepower: 228,
    acceleration: '6.1s 0-100',
    topSpeed: '246 km/s',
    dailyPrice: 3900,
    discountPrice: 3450,
    features: [
      'Go-Kart Hissi Veren Sertleştirilmiş Spor Süspansiyon',
      'Brembo 4 Pistonlu JCW Spor Frenler',
      'Ortadan Çift Çıkışlı Paslanmaz Çelik Spor Egzoz',
      'Harman Kardon Hi-Fi Ses Sistemi',
      'Dinamik Amortisör Kontrolü (DDC)',
    ],
    description:
      'Efsanevi Go-Kart hissinin en güçlü hali. Çevik direksiyon tepkisi, sert spor süspansiyonu ve patlamalı spor egzoz sesiyle şehir sokaklarında rakipsiz sürüş neşesi.',
    isAvailable: true,
    isPopular: false,
    rating: 4.89,
    reviewCount: 53,
    location: 'Muğla, Bodrum',
  },

  // ==========================================
  // 6. VAN (VIP MINIBUS & EXECUTIVE SHUTTLES)
  // ==========================================
  {
    brand: 'Mercedes-Benz',
    model: 'V-Class Maybach VIP Lounge',
    year: 2025,
    category: 'Van',
    transmission: 'Otomatik',
    fuelType: 'Dizel',
    capacity: 7,
    tankOrBattery: '70 L',
    horsepower: 237,
    acceleration: '7.8s 0-100',
    topSpeed: '215 km/s',
    dailyPrice: 14500,
    discountPrice: 12800,
    features: [
      'Maybach First-Class Yatan Masajlı VIP Koltuklar',
      '43 inç 4K Akıllı Asansörlü Ara Bölme Ekranı',
      'PlayStation 5 ve Apple TV Entegre Multimedya',
      'Nespresso Kahve Makinesi ve Şampanya Soğutucu',
      'Yıldızlı Tavan ve Ambiyans Aydınlatma Sistemi',
    ],
    description:
      'Tekerlekli özel jet konforu. Maybach sınıfı tam yatar masajlı koltuklar, 43 inç gizlenebilir sinema ekranı, PS5 oyun konsolu ve özel vale karşılama hizmetiyle VIP transferin zirvesi.',
    isAvailable: true,
    isPopular: true,
    rating: 4.99,
    reviewCount: 88,
    location: 'İstanbul, Havalimanı (IST) VIP Terminal',
  },
  {
    brand: 'Mercedes-Benz',
    model: 'V-Class Exclusive',
    year: 2024,
    category: 'Van',
    transmission: 'Otomatik',
    fuelType: 'Dizel',
    capacity: 7,
    tankOrBattery: '70 L',
    horsepower: 237,
    acceleration: '8.2s 0-100',
    topSpeed: '210 km/s',
    dailyPrice: 9800,
    discountPrice: 8600,
    features: [
      'Yüz Yüze Toplantı Düzenli Konferans Koltukları',
      'Panoramik Açılabilir Çift Cam Tavan',
      'Burmester Surround Ses Sistemi',
      'Katlanabilir Alüminyum Çalışma Masası',
      'Çift Elektrikli Sürgülü Yan Kapılar',
    ],
    description:
      'Geniş aile seyahatleri ve kurumsal yönetim heyetleri için ideal lüks taşıyıcı. Karşılıklı bakan konferans koltukları, çalışma masası ve sessiz uzun yol sürüşü.',
    isAvailable: true,
    isPopular: true,
    rating: 4.94,
    reviewCount: 72,
    location: 'Antalya, Havalimanı (AYT) VIP',
  },
  {
    brand: 'Volkswagen',
    model: 'Caravelle Highline VIP',
    year: 2024,
    category: 'Van',
    transmission: 'Otomatik',
    fuelType: 'Dizel',
    capacity: 8,
    tankOrBattery: '80 L',
    horsepower: 204,
    acceleration: '9.1s 0-100',
    topSpeed: '201 km/s',
    dailyPrice: 6500,
    discountPrice: 5800,
    features: [
      '8+1 Kişilik Geniş Konforlu Yolcu Kapasitesi',
      'Climatronic 3 Bölgeli Bağımsız Dijital Klima',
      'Deri Kaplama Ergonomik VIP Yolcu Koltukları',
      'Elektrikli Vakumlu Sürgülü Kapı ve Basamak',
      'Discover Pro Büyük Ekranlı Navigasyon',
    ],
    description:
      'Geniş gruplar ve kalabalık aileler için ferah ve güvenilir VIP ulaşım. 8+1 kişilik cömert oturma kapasitesi, devasa bagaj alanı ve güçlü çift turbo dizel motor.',
    isAvailable: true,
    isPopular: false,
    rating: 4.88,
    reviewCount: 59,
    location: 'İzmir, Adnan Menderes Havalimanı',
  },
  {
    brand: 'Lexus',
    model: 'LM 350h President VIP Lounge',
    year: 2025,
    category: 'Van',
    transmission: 'Otomatik',
    fuelType: 'Hibrit',
    capacity: 4,
    tankOrBattery: '60 L',
    horsepower: 250,
    acceleration: '8.7s 0-100',
    topSpeed: '190 km/s',
    dailyPrice: 18500,
    discountPrice: 16500,
    features: [
      '48 inç Geniş Ekranlı Arka Sinema Bölmesi',
      'L-Aniline Özel Deri Sıfır Yerçekimi Koltuklar',
      'Mark Levinson 3D Ses Sistemi (23 Hoparlör)',
      'Akıllı Termal Sıcaklık Tarama Sensörü',
      'Elektrokromik Karartmalı Cam Bölme',
    ],
    description:
      'Japon Omotenashi misafirperverlik felsefesiyle inşa edilen lüks saray. 48 inçlik sinema ekranı, sıfır yerçekimi havalandırmalı masaj koltukları ve hibrit sessizliği.',
    isAvailable: true,
    isPopular: false,
    rating: 4.97,
    reviewCount: 36,
    location: 'İstanbul, Maslak Finans Merkezi',
  },
];

export async function POST() {
  try {
    await connectToDatabase();

    // Check if cars already exist
    const count = await Car.countDocuments();
    if (count > 0) {
      // Refresh database with canonical seed data
      await Car.deleteMany({});
    }

    const insertedCars = await Car.insertMany(SEED_CARS);

    return NextResponse.json({
      success: true,
      message: `Veritabanı ${insertedCars.length} adet araç ile başarıyla güncellendi (Fiyatlar Türk Lirası cinsindendir).`,
      count: insertedCars.length,
    });
  } catch (error: unknown) {
    console.error('Seed API error:', error);
    const message =
      error instanceof Error ? error.message : 'Veritabanı doldurulamadı';
    return NextResponse.json(
      { success: false, error: message },
      { status: 500 }
    );
  }
}

export async function GET() {
  // Allow GET trigger for convenient browser or test invocation
  return POST();
}
